extend = [ { path = "target/rust-driver-makefile.toml" }, { path = "target/rust-driver-sample-makefile.toml" } ]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
WDK_BUILD_ADDITIONAL_INFVERIF_FLAGS = "/msft"

[config]
load_script = '''
#!@rust
//! ```cargo
//! [dependencies]
//! wdk-build = { git = "https://github.com/svasista-ms/windows-drivers-rs.git", branch = "move-infverif-latest" }
//! ```
#![allow(unused_doc_comments)]

wdk_build::cargo_make::load_rust_driver_makefile()?;
wdk_build::cargo_make::load_rust_driver_sample_makefile()?;
'''

[tasks.default]
# Since this worspace contains both driver and non-driver crates, we need to explicitly specify `build` so that non-driver crates are still compiled
clear = true
dependencies = ["build", "package-driver-flow"]
